### ISSUE TITLE
Url NoxItem

### ISSUE THREAD

**Issue by alorma** [pedrovgs/Nox#5]
Hey

NoxView allow to load images in my own choosed library?

**Comment by pedrovgs** [comment]
The library used to load resources is Picasso. If you want to support different libraries to download images the project is ready but we will have to add some code. In fact, I started this project using Glide instead of Picasso :)

**Comment by alorma** [comment]
Ok :)

It will be great to use any lib. I particullary use UIL

**Comment by pedrovgs** [comment]
To use any other library you have to implement ImageLoader interface and modify NoxView code to be able to use a custom ImageLoader instance. It's easy, you can send me a PR with the change if you need it :)

This is the interface to implement: https://github.com/pedrovgs/Nox/blob/master/nox/src/main/java/com/github/pedrovgs/nox/imageloader/ImageLoader.java
