### ISSUE TITLE
Add library "about"

### ISSUE THREAD

**Issue by alorma** [pedrovgs/Nox#6]
As this library do, add library data to be used in about sections:

https://github.com/mikepenz/AboutLibraries

**Comment by pedrovgs** [comment]
Hi!

I'm not going to publish the APK in Google Play or add an about section in the app. The libraries used in this project are in the README.md. Thanks anyway!

**Comment by alorma** [comment]
Uhmmm.

That's not what AboutLibraries do.

This library "scrap" strings from library, so i can see in the screen with other libs.

Not add about in the lib... add about fields to be read by other libs
